from .autenticacion import Login as LoginResource
from .autenticacion import Logout as LogoutResource
from .notificaciones import Notificacion as NotificacionesResource
from .pedidos import Pedido as PedidoResource
from .pedidos import Pedidos as PedidosResource
from .pedidos import PedidosUsuario as PedidosUsuarioResource
from .productos import Producto as ProductoResource
from .productos import Productos as ProductosResource
from .productos import ProductoValoraciones as ProductoValoracionesResource
from .usuarios import Usuario as UsuarioResource
from .usuarios import Usuarios as UsuariosResource
from .valoraciones import Valoracion as ValoracionResource
from .valoraciones import VerificarCompraProducto as VerificarCompraProductoResource
from .valoraciones import ValoracionesRecientes as ValoracionesRecientesResource
from .categorias import Categorias as CategoriasResource
from .categorias import Categoria as CategoriaResource
from .campanas import Campanas as CampanasResource
from .campanas import Campana as CampanaResource
from .campanas import CampanasActivas as CampanasActivasResource